//go:build e2e

package scenarios

import (
	"encoding/json"
	"fmt"
	"net/http"
	"reflect"
	"sort"
	"testing"
	"time"

	"github.com/authplane/authserver/e2e"
)

// TestAgentIdentity_MintIssuance_ClaimsInJWT_AndOnIssuance verifies
// that the unified Mint dispatch ( / ) carries the
// agent_id claim through to the JWT AND to the persisted issuances row
// (the data model).
//
// Setup:
//   - Two Mint resources, mcp-a and mcp-b.
//   - Agent client (public) drives auth-code → user JWT with
//     client_id=agent.
//   - mcp-a (confidential, agent-flagged) does the token-exchange call
//     targeting mcp-b. Because mcp-a is itself an agent, the resulting
//     issuance JWT carries agent_id = mcp-a's client_id.
func TestAgentIdentity_MintIssuance_ClaimsInJWT_AndOnIssuance(t *testing.T) {
	scopes := []string{"tools/echo"}
	h, servers := e2e.SetupE2E(t, e2e.HarnessConfig{
		EnableAdminAPI:             true,
		EnableTokenExchange:        true,
		TokenExchangeMaxChainDepth: 5,
	}, scopes, scopes)
	rsA := servers[0]
	rsB := servers[1]
	h.RegisterScope(rsA.URI, "tools/echo", "Echo tool A")
	h.RegisterScope(rsB.URI, "tools/echo", "Echo tool B")

	const email = "alice-agent-mint@example.com"
	const password = "pass123"
	h.CreateUser(email, password)

	// Agent (public, PKCE) — the bearer of alice's user token.
	// client_id is auto-generated by the AS; the test consumes the
	// returned value.
	agentID := h.AdminCreatePublicClient(
		"agent-identity-mint webapp",
		[]string{"authorization_code"},
		"tools/echo",
		nil,
	)

	// mcp-a as a confidential, agent-flagged client (auto-generated id).
	mcpAID, mcpASecret := h.RegisterAgentClient(
		[]string{"urn:ietf:params:oauth:grant-type:token-exchange"},
		"tools/echo",
		"MCP A as Agent",
	)

	// Resolve mcp-1 via the public admin API so we
	// can match its ID on the issuances row below. Replaces the
	// Gate-0 shortcut h.ResourceStore().GetBySlug. We don't need mcp-0's
	// id — it's only used to drive consent, which RunFlowC1Consent looks
	// up by slug internally.
	mcpBRes := h.AdminGetResourceBySlug("mcp-1")

	// mcp-a delegates alice's agent-issued token onward to mcp-b. The
	// consent grant it spends belongs to the agent, so the operator of
	// mcp-b has to name mcp-a as a permitted delegate.
	h.AdminAllowExchangeClient("mcp-1", mcpAID)

	// Drive consent through the public surface (auth-code grant against
	// /authorize → /consent) for each MCP resource. Replaces the
	// Gate-0 shortcut h.SeedConsentGrant. The returned auth code is
	// unused — only the consent_grants row side-effect matters here; the
	// real auth-code+token round-trip is exercised below via
	// agentClient.FullFlow.
	h.RunFlowC1Consent(email, password, agentID, "http://localhost:9999/callback", "mcp-0", []string{"tools/echo"}, []string{"tools/echo"})
	h.RunFlowC1Consent(email, password, agentID, "http://localhost:9999/callback", "mcp-1", []string{"tools/echo"}, []string{"tools/echo"})

	// 1. User JWT via the agent's auth-code flow.
	agentClient := e2e.NewMCPClient(t, h, rsA, agentID, "http://localhost:9999/callback")
	userTokens := agentClient.FullFlow(email, password, "tools/echo", false)

	// 2. Token-exchange to mcp-b via mcp-a (delegation).
	exch := h.TokenExchangeWithResource(
		mcpAID, mcpASecret,
		userTokens.AccessToken, "urn:ietf:params:oauth:token-type:access_token",
		"tools/echo",
		"mcp-1",
	)
	if exch.AccessToken == "" {
		t.Fatal("expected exchanged access token")
	}

	// 3. JWT carries agent_id —  wiring contract.
	claims := parseJWTClaims(t, exch.AccessToken)
	if claims["agent_id"] != mcpAID {
		t.Errorf("JWT agent_id = %v, want %q", claims["agent_id"], mcpAID)
	}

	// 4. Issuance row carries the same agent_id. drive via the
	// admin issuances HTTP path instead of h.IssuanceStore().ListForActor.
	issuances := listIssuancesForActor(t, h, mcpAID, time.Now().Add(-1*time.Hour))
	var found bool
	for _, iss := range issuances {
		if iss.ResourceID != mcpBRes.ID {
			continue
		}
		if iss.AgentID != mcpAID {
			t.Errorf("issuances.agent_id = %q, want %q", iss.AgentID, mcpAID)
		}
		// AgentChain may be empty on a delegation without an
		// actor_token; the contract is "persisted byte-exactly with
		// the JWT claim shape", which here is the empty case.
		found = true
		break
	}
	if !found {
		t.Errorf("expected an issuance row for actor=%s resource=%s", mcpAID, mcpBRes.ID)
	}
}

// TestAgentIdentity_BrokerIssuance_ClaimsOnIssuance_NotInWireToken
// verifies that the Broker dispatch path ( / ):
//
//  1. Returns the upstream's opaque token unchanged on the wire.
//  2. Persists agent_id on the issuances row anyway, per
//     the data model — Broker tokens cannot carry Authplane claims
//     because they're the upstream's bytes, but the AS still records
//     the chain origin for forensics.
func TestAgentIdentity_BrokerIssuance_ClaimsOnIssuance_NotInWireToken(t *testing.T) {
	const upstreamSlug = "github-agent-id"
	const email = "alice-agent-broker@example.com"
	const password = "pass123"
	// slug and client_id are decoupled. The actor MCP's Mint
	// Resource is keyed by the slug below; the agent's auto-generated
	// client_id is bound to it via policy.runtime.client_ids.
	mcpServerSlug := fmt.Sprintf("mcp-server-%d", time.Now().UnixNano())

	scopes := []string{"tools/echo"}
	h, servers := e2e.SetupE2E(t, e2e.HarnessConfig{
		EnableAdminAPI:             true,
		EnableTokenExchange:        true,
		TokenExchangeMaxChainDepth: 5,
		Connectors: []e2e.ConnectorConfig{
			{Service: upstreamSlug, Scopes: []string{"repo"}, AccessToken: "gho_agent_id_broker", RefreshToken: "ghr_agent_id_broker", ExpiresIn: 3600},
		},
	}, scopes)
	rs := servers[0]

	h.RegisterScope(rs.URI, "tools/echo", "Echo tool")
	h.CreateUser(email, password)

	// Web app as the user-bearing client (PKCE).
	webAppClientID := h.AdminCreatePublicClient(
		"agent-identity-broker webapp",
		[]string{"authorization_code"},
		"tools/echo",
		nil,
	)
	// MCP server as a confidential, agent-flagged token-exchange caller.
	mcpServerClientID, mcpSecret := h.AdminCreateAgentClient(
		"agent-identity-broker MCP server",
		[]string{"urn:ietf:params:oauth:grant-type:token-exchange"},
		"tools/echo repo",
		"MCP Server as Agent",
	)

	mcpClient := e2e.NewMCPClient(t, h, rs, webAppClientID, "http://localhost:9999/callback")
	tokens := mcpClient.FullFlow(email, password, "tools/echo", false)

	// Register the upstream broker provider + Broker resource via the
	// public admin API, then drive the /connect dance to persist the
	// BrokerGrant. Replaces the Gate-0 shortcut h.SeedConnection
	// (which directly wrote brokerProviderStore + resourceStore +
	// brokerGrantStore).
	mockBase := h.MockUpstreamURL(upstreamSlug)
	h.AdminCreateBrokerProvider(e2e.CreateBrokerProviderSpec{
		Slug:        upstreamSlug,
		DisplayName: upstreamSlug,
		Protocol:    "oauth",
		ConfigData: map[string]any{
			"client_id":         "mock-client-id",
			"client_secret_ref": "CONNECTOR_E2E_MOCK_SECRET",
			"authorize_url":     mockBase + "/authorize",
			"token_url":         mockBase + "/token",
			"response_format":   "standard",
		},
	})
	h.AdminCreateResource(e2e.CreateResourceSpec{
		Slug:               upstreamSlug,
		URI:                "https://" + upstreamSlug + ".test",
		BackendKind:        "broker",
		BrokerProviderSlug: upstreamSlug,
		DisplayName:        upstreamSlug,
		Scopes:             []e2e.AdminScope{{Name: "repo", Upstream: "repo"}},
	})
	h.RunFlowConnect(email, password, upstreamSlug)

	// register the actor MCP's Mint Resource via the admin API
	// and bind the agent's auto-generated client_id via
	// policy.runtime.client_ids so dispatchBroker's agent-attestation
	// gate can map req.ClientID back to this Resource.
	h.AdminCreateResource(e2e.CreateResourceSpec{
		Slug:        mcpServerSlug,
		URI:         "https://" + mcpServerSlug + ".test",
		BackendKind: "mint",
		DisplayName: "mcp:" + mcpServerSlug,
		Scopes:      []e2e.AdminScope{{Name: "tools/echo"}, {Name: "repo"}},
		Policy: &e2e.AdminPolicy{
			Runtime: e2e.AdminRuntimePolicy{ClientIDs: []string{mcpServerClientID}},
		},
	})
	// fronting link from the JWT-issuing Mint (mcp-0) to the
	// Broker target so dispatchFrontedBroker handles the exchange.
	h.AdminCreateFrontingLink(e2e.CreateFrontingLinkSpec{
		Source:   "mcp-0",
		Target:   upstreamSlug,
		ScopeMap: map[string][]string{"tools/echo": {"repo"}},
	})
	h.RunFlowC1Consent(email, password, webAppClientID, "http://localhost:9999/callback", mcpServerSlug, []string{"tools/echo", "repo"}, []string{"tools/echo", "repo"})

	exch := h.TokenExchangeWithResource(
		mcpServerClientID, mcpSecret,
		tokens.AccessToken, "urn:ietf:params:oauth:token-type:access_token",
		"repo",
		upstreamSlug,
	)
	// 1. Wire token is the upstream's opaque value (NOT a JWT — no
	// agent_id can be embedded). With the public-API path the broker
	// adapter refreshes via grant_type=refresh_token, which the mock
	// upstream echoes as the access_token — so what comes back on the
	// wire is the connector's RefreshToken, not its AccessToken. (The
	// pre- SeedConnection shortcut wrote the test's expected
	// access-token string into the encrypted credential's refresh_token
	// slot, which produced the same effect under a different label.)
	if exch.AccessToken != "ghr_agent_id_broker" {
		t.Errorf("vended access_token = %q, want ghr_agent_id_broker", exch.AccessToken)
	}

	// 2. Issuance row records agent_id for forensics. drive via
	// the admin issuances HTTP path instead of
	// h.IssuanceStore().ListForActor.
	// with fronting, dispatchFrontedBroker substitutes the source
	// slug ("mcp-0") for the agent's client_id in the issuance.client_id
	// field (Option β). The agent's identity still lives in agent_id.
	issuances := listIssuancesForActor(t, h, "mcp-0", time.Now().Add(-1*time.Hour))
	var found bool
	for _, iss := range issuances {
		if iss.BackendKind != "broker" {
			continue
		}
		if iss.AgentID != mcpServerClientID {
			t.Errorf("broker issuance agent_id = %q, want %q", iss.AgentID, mcpServerClientID)
		}
		gotScopes := append([]string(nil), iss.Scopes...)
		sort.Strings(gotScopes)
		if !reflect.DeepEqual(gotScopes, []string{"repo"}) {
			t.Errorf("broker issuance scopes = %v, want [repo]", gotScopes)
		}
		found = true
		break
	}
	if !found {
		t.Error("expected one Broker issuance for actor MCP client; found none")
	}
}

// adminIssuanceView mirrors the subset of internal/admin/dto.IssuanceView
// the agent-identity tests actually read. Defined locally so the test
// does not import internal/admin/dto (Gate 0).
type adminIssuanceView struct {
	ID          string   `json:"id"`
	ClientID    string   `json:"client_id"`
	ResourceID  string   `json:"resource_id"`
	AgentID     string   `json:"agent_id"`
	BackendKind string   `json:"backend_kind"`
	Scopes      []string `json:"scopes"`
}

// listIssuancesForActor calls GET /admin/issuances?client=<id>&since=<rfc3339>
// and returns the parsed issuance rows. Replaces the Gate-0
// shortcut h.IssuanceStore().ListForActor with the public admin path.
func listIssuancesForActor(t *testing.T, h *e2e.TestHarness, actorClientID string, since time.Time) []adminIssuanceView {
	t.Helper()
	path := fmt.Sprintf("/admin/issuances?client=%s&since=%s", actorClientID, since.UTC().Format(time.RFC3339))
	resp := h.AdminRequest("GET", path, nil)
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("GET %s: status %d", path, resp.StatusCode)
	}
	var body struct {
		Issuances []adminIssuanceView `json:"issuances"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&body); err != nil {
		t.Fatalf("decode admin issuances response: %v", err)
	}
	return body.Issuances
}
