//go:build e2e

package scenarios

import (
	"net/url"
	"testing"

	"github.com/authplane/authserver/e2e"
)

// Inline RFC 8693 URN literals replace the internal/domain/token constants
// (token.GrantTypeTokenExchange, token.TokenTypeAccessToken). Keeping the
// raw strings here matches the wire format the public OAuth surface
// already speaks and avoids dragging the internal/ package into a Gate-0
// e2e file. See.
const (
	tokenTypeAccessToken = "urn:ietf:params:oauth:token-type:access_token"
)

// TestConnectionVend_ViaTokenExchange_HappyPath verifies the full flow:
//  1. User logs in via web-app → gets user access token (sub = user_id)
//  2. MCP server exchanges user token with resource=github → gets stored GitHub token
func TestConnectionVend_ViaTokenExchange_HappyPath(t *testing.T) {
	// Stable, deterministic client IDs (replaces crypto.GenerateClientID).
	// Values are slug-safe and unique across the three tests in this
	// file so runs in parallel mode don't collide on the derived
	// resource slug for the actor MCP.
	// client_ids are auto-generated by the AS; only the slug is
	// operator-meaningful.
	const mcpResourceSlug = "mcp-conntx-happy-0001"

	scopes := []string{"tools/echo"}
	h, servers := e2e.SetupE2E(t, e2e.HarnessConfig{
		EnableAdminAPI:             true,
		EnableTokenExchange:        true,
		TokenExchangeMaxChainDepth: 5,
		Connectors: []e2e.ConnectorConfig{
			// The mock upstream's POST /token handler echoes the
			// stored refresh_token back as the access_token on
			// grant_type=refresh_token (the Vend path the
			// brokerproto/oauth adapter uses). Setting RefreshToken
			// to "gho_vend_via_exchange_token" is what makes the
			// L77 assertion pass — that value is persisted on the
			// BrokerGrant via RunFlowConnect and later vended out.
			// AccessToken is set to the same string for consistency
			// (it's what the mock returns on the original
			// authorization_code call during the connect dance).
			// RefreshToken is also required by the brokerproto/oauth
			// adapter, which rejects upstream responses missing one.
			{
				Service:      "github",
				Scopes:       []string{"repo", "read:user"},
				AccessToken:  "gho_vend_via_exchange_token",
				RefreshToken: "gho_vend_via_exchange_token",
				ExpiresIn:    3600,
			},
		},
	}, scopes)
	rs := servers[0]

	h.RegisterScope(rs.URI, "tools/echo", "Echo tool")

	// 1. Create a user.
	h.CreateUser("alice@example.com", "password123")

	// 2. Create web-app as public client (auth code + PKCE, no secret needed).
	webAppClientID := h.AdminCreatePublicClient("conntx webapp", []string{"authorization_code"}, "tools/echo", nil)

	// 3. Create MCP server as confidential client (for token exchange with client_secret).
	mcpServerClientID, mcpSecret := h.AdminCreateConfidentialClient("conntx mcp server", []string{"urn:ietf:params:oauth:grant-type:token-exchange"}, "tools/echo")

	// 4. Full auth code flow to get a user token (sub = userID, client_id = webAppClientID).
	mcpClient := e2e.NewMCPClient(t, h, rs, webAppClientID, "http://localhost:9999/callback")
	tokens := mcpClient.FullFlow("alice@example.com", "password123", "tools/echo", true)
	if tokens.AccessToken == "" {
		t.Fatal("expected non-empty user access_token from auth code flow")
	}

	// 5. Register the broker provider + Broker resource via the public
	// admin API (replaces h.SeedConnection's get-or-create shortcut).
	// The config_data wires the brokerproto/oauth adapter at the
	// in-process mock upstream — same shape as connect_flow_test.go.
	mockBase := h.MockUpstreamURL("github")
	h.AdminCreateBrokerProvider(e2e.CreateBrokerProviderSpec{
		Slug:        "github",
		DisplayName: "github",
		Protocol:    "oauth",
		ConfigData: map[string]any{
			"client_id":         "mock-client-id",
			"client_secret_ref": "CONNECTOR_E2E_MOCK_SECRET",
			"authorize_url":     mockBase + "/authorize",
			"token_url":         mockBase + "/token",
			"response_format":   "standard",
		},
	})
	h.AdminCreateResource(e2e.CreateResourceSpec{
		Slug:               "github",
		URI:                "https://github.test",
		BackendKind:        "broker",
		BrokerProviderSlug: "github",
		DisplayName:        "github",
		Scopes: []e2e.AdminScope{
			{Name: "repo", Upstream: "repo"},
			{Name: "read:user", Upstream: "read:user"},
		},
	})

	// 5b. Drive the /connect dance via the public surface to persist
	// the BrokerGrant (replaces h.SeedConnection's direct store write).
	h.RunFlowConnect("alice@example.com", "password123", "github")

	// 5c. Register the actor MCP as a Mint resource and grant consent
	// via the public C1 (per-MCP) consent flow. This activates
	// dispatchBroker's bound-B + bound-C gates. bind the agent's
	// auto-generated client_id to this Mint Resource via
	// policy.runtime.client_ids so dispatchBroker can resolve req.ClientID.
	h.AdminCreateResource(e2e.CreateResourceSpec{
		Slug:        mcpResourceSlug,
		URI:         "https://" + mcpResourceSlug + ".test",
		BackendKind: "mint",
		DisplayName: "mcp:" + mcpResourceSlug,
		Scopes: []e2e.AdminScope{
			{Name: "tools/echo"},
			{Name: "repo"},
		},
		Policy: &e2e.AdminPolicy{
			Runtime: e2e.AdminRuntimePolicy{ClientIDs: []string{mcpServerClientID}},
		},
	})
	// declare the fronting link from the JWT-issuing Mint
	// (rs/mcp-0) to the broker target so dispatchFrontedBroker handles
	// the exchange. Without this, dispatchBroker now returns
	// FrontingLinkMissingError instead of falling through to bound-B.
	h.AdminCreateFrontingLink(e2e.CreateFrontingLinkSpec{
		Source:   "mcp-0",
		Target:   "github",
		ScopeMap: map[string][]string{"tools/echo": {"repo"}},
	})
	attestationScopes := []string{"tools/echo", "repo"}
	h.RunFlowC1Consent(
		"alice@example.com", "password123",
		webAppClientID, "http://localhost:9999/callback",
		mcpResourceSlug, attestationScopes, attestationScopes,
	)

	// 6. MCP server exchanges the user token with resource=github.
	resp := h.TokenExchangeWithResource(
		mcpServerClientID, mcpSecret,
		tokens.AccessToken, tokenTypeAccessToken,
		"repo",   // third-party scope
		"github", // upstream broker resource (slug)
	)

	// 7. Verify: should be the stored third-party token, not an authserver JWT.
	if resp.AccessToken != "gho_vend_via_exchange_token" {
		t.Errorf("access_token = %q, want gho_vend_via_exchange_token", resp.AccessToken)
	}
	if resp.TokenType != "Bearer" {
		t.Errorf("token_type = %q, want Bearer", resp.TokenType)
	}
	if resp.IssuedTokenType != tokenTypeAccessToken {
		t.Errorf("issued_token_type = %q, want %q", resp.IssuedTokenType, tokenTypeAccessToken)
	}
	if resp.Scope != "repo" {
		t.Errorf("scope = %q, want repo", resp.Scope)
	}
}

// TestConnectionVend_ViaTokenExchange_NotConnected verifies the error when user has no Connect flow.
func TestConnectionVend_ViaTokenExchange_NotConnected(t *testing.T) {
	const mcpResourceSlug = "mcp-conntx-notcon-0002"

	scopes := []string{"tools/echo"}
	h, servers := e2e.SetupE2E(t, e2e.HarnessConfig{
		EnableAdminAPI:             true,
		EnableTokenExchange:        true,
		TokenExchangeMaxChainDepth: 5,
		Connectors: []e2e.ConnectorConfig{
			{Service: "github", Scopes: []string{"repo"}, AccessToken: "gho_mock", RefreshToken: "ghr_notconnected", ExpiresIn: 3600},
		},
	}, scopes)
	rs := servers[0]

	h.RegisterScope(rs.URI, "tools/echo", "Echo tool")
	h.CreateUser("bob@example.com", "password123")

	webAppClientID := h.AdminCreatePublicClient("conntx-notcon webapp", []string{"authorization_code"}, "tools/echo", nil)
	mcpServerClientID, mcpSecret := h.AdminCreateConfidentialClient("conntx-notcon mcp", []string{"urn:ietf:params:oauth:grant-type:token-exchange"}, "tools/echo")

	mcpClient := e2e.NewMCPClient(t, h, rs, webAppClientID, "http://localhost:9999/callback")
	tokens := mcpClient.FullFlow("bob@example.com", "password123", "tools/echo", true)

	// Register the broker provider + Broker resource for "github" but
	// skip RunFlowConnect — no BrokerGrant exists. dispatchBroker will
	// pass operator + agent + bound-C gates (the actor-MCP attestation
	// is granted below) and reach BrokerIssuer.Issue, which finds no
	// active grant and returns ConsentRequiredError keyed on
	// provider.Slug ("github"). The handler synthesizes the
	// /connect/github URL the assertion below pins.
	mockBase := h.MockUpstreamURL("github")
	h.AdminCreateBrokerProvider(e2e.CreateBrokerProviderSpec{
		Slug:        "github",
		DisplayName: "github",
		Protocol:    "oauth",
		ConfigData: map[string]any{
			"client_id":         "mock-client-id",
			"client_secret_ref": "CONNECTOR_E2E_MOCK_SECRET",
			"authorize_url":     mockBase + "/authorize",
			"token_url":         mockBase + "/token",
			"response_format":   "standard",
		},
	})
	h.AdminCreateResource(e2e.CreateResourceSpec{
		Slug:               "github",
		URI:                "https://github.test",
		BackendKind:        "broker",
		BrokerProviderSlug: "github",
		DisplayName:        "github",
		Scopes:             []e2e.AdminScope{{Name: "repo", Upstream: "repo"}},
	})

	// Register actor MCP + per-MCP consent so dispatchBroker reaches
	// BrokerIssuer.Issue ( bound-C requires the attestation to
	// cover the requested upstream scope, so include "repo").
	// bind the agent's auto-generated client_id via runtime.client_ids.
	h.AdminCreateResource(e2e.CreateResourceSpec{
		Slug:        mcpResourceSlug,
		URI:         "https://" + mcpResourceSlug + ".test",
		BackendKind: "mint",
		DisplayName: "mcp:" + mcpResourceSlug,
		Scopes: []e2e.AdminScope{
			{Name: "tools/echo"},
			{Name: "repo"},
		},
		Policy: &e2e.AdminPolicy{
			Runtime: e2e.AdminRuntimePolicy{ClientIDs: []string{mcpServerClientID}},
		},
	})
	// fronting link required for dispatchFrontedBroker to handle
	// the exchange. The "no broker_grant" failure is detected inside
	// BrokerIssuer.Issue regardless of dispatch path.
	h.AdminCreateFrontingLink(e2e.CreateFrontingLinkSpec{
		Source:   "mcp-0",
		Target:   "github",
		ScopeMap: map[string][]string{"tools/echo": {"repo"}},
	})
	attestationScopes := []string{"tools/echo", "repo"}
	h.RunFlowC1Consent(
		"bob@example.com", "password123",
		webAppClientID, "http://localhost:9999/callback",
		mcpResourceSlug, attestationScopes, attestationScopes,
	)

	// Don't seed a broker grant — exchange should fail with consent_required.
	oe := h.TokenExchangeWithResourceExpectError(
		mcpServerClientID, mcpSecret,
		tokens.AccessToken, tokenTypeAccessToken,
		"repo",
		"github",
	)
	if oe.Error != "consent_required" {
		t.Errorf("error = %q, want consent_required", oe.Error)
	}
	wantDesc := "Authorize access to github"
	if oe.ErrorDescription != wantDesc {
		t.Errorf("error_description = %q, want %q", oe.ErrorDescription, wantDesc)
	}
	// fronted dispatch builds the connect URL without the
	// `resource=<broker-slug>` hint (the source slug is implicit in the
	// fronting link). The legacy bound-B path used to embed it.
	wantURL := h.Issuer + "/connect/github?return_url=" + url.QueryEscape(h.Issuer+"/connections")
	if oe.ConsentURL != wantURL {
		t.Errorf("consent_url = %q, want %q", oe.ConsentURL, wantURL)
	}
}

// ( made the legacy unknown-resource fall-through unreachable
// — registered Mint resources now require an explicit consent_grants_unified
// row before dispatchMint mints. TestConnectionVend_ViaTokenExchange_NonConnectionResource
// was deleted in the review-pass refinements; the equivalent positive
// coverage lives in token_exchange_dispatch_test.go.)
