//go:build e2e

package scenarios

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"testing"
	"time"

	"github.com/go-jose/go-jose/v4"

	"github.com/authplane/authserver/e2e"
	"github.com/authplane/go-sdk/core/authplane"
)

// Inline RFC 8693 URN literals replace the internal/domain/token
// constants (token.GrantTypeTokenExchange, token.TokenTypeAccessToken).
// Same pattern as connection_token_exchange_test.go and
// agent_identity_unified_test.go. See / Gate 0.
const (
	dpopGrantTypeTokenExchange = "urn:ietf:params:oauth:grant-type:token-exchange"
	dpopTokenTypeAccessToken   = "urn:ietf:params:oauth:token-type:access_token"
)

// TestDPoP_UnifiedMintDispatch_JKTPersistsOnIssuance verifies that a
// DPoP proof presented to /oauth/token grant_type=token-exchange
// targeting a Mint resource:
//
//  1. Yields a DPoP-bound access token (JWT with cnf.jkt = thumbprint
//     of the proof's key, token_type=DPoP).
//  2. Persists dpop_jkt on the issuances row that the dispatch wrote.
//
// This is the  /  /  contract: DPoP plumbing reaches
// the unified Mint dispatch (not just the legacy client_credentials
// path).
func TestDPoP_UnifiedMintDispatch_JKTPersistsOnIssuance(t *testing.T) {
	scopes := []string{"tools/echo"}
	h, servers := e2e.SetupE2E(t, e2e.HarnessConfig{
		EnableAdminAPI:             true,
		EnableTokenExchange:        true,
		TokenExchangeMaxChainDepth: 5,
		EnableDPoP:                 true,
	}, scopes, scopes)
	rsA := servers[0]
	rsB := servers[1]
	h.RegisterScope(rsA.URI, "tools/echo", "Echo tool A")
	h.RegisterScope(rsB.URI, "tools/echo", "Echo tool B")

	const email = "alice-dpop-mint@example.com"
	const password = "pass123"
	h.CreateUser(email, password)

	// Agent (public, PKCE) drives the auth-code flow → JWT with
	// sub=alice, client_id=agentID. mcp-a (confidential) does the
	// token-exchange call → dispatchMint targets mcp-b.
	// client_ids are auto-generated by the AS.
	agentID := h.AdminCreatePublicClient("dpop-mint webapp", []string{"authorization_code"}, "tools/echo", nil)
	mcpAClientID, mcpASecret := h.AdminCreateConfidentialClient("dpop-mint actor MCP", []string{dpopGrantTypeTokenExchange}, "tools/echo")

	// Resolve mcp-1 via the public admin API so we
	// can match its ID on the issuances row below. Replaces the
	// Gate-0 shortcut h.ResourceStore().GetBySlug. mcp-0's id is not
	// needed — RunFlowC1Consent looks up by slug internally.
	mcpBRes := h.AdminGetResourceBySlug("mcp-1")

	// mcp-a delegates the agent's token to mcp-b, spending the agent's
	// consent grant — the operator authorizes that by naming mcp-a here.
	h.AdminAllowExchangeClient("mcp-1", mcpAClientID)

	// Drive consent through the public surface (auth-code grant against
	// /authorize → /consent) for each MCP resource. Replaces the
	// Gate-0 shortcut h.SeedConsentGrant. The returned auth code is
	// unused — only the consent_grants row side-effect matters here.
	h.RunFlowC1Consent(email, password, agentID, "http://localhost:9999/callback", "mcp-0", []string{"tools/echo"}, []string{"tools/echo"})
	h.RunFlowC1Consent(email, password, agentID, "http://localhost:9999/callback", "mcp-1", []string{"tools/echo"}, []string{"tools/echo"})

	// Run the agent's auth-code flow against mcp-a so the resulting
	// JWT carries client_id=agentID, sub=alice. (No DPoP on this leg —
	// the test target is the unified Mint dispatch.)
	agentClient := e2e.NewMCPClient(t, h, rsA, agentID, "http://localhost:9999/callback")
	userTokens := agentClient.FullFlow(email, password, "tools/echo", false)

	// Build a DPoP signer and POST the token-exchange targeting mcp-b.
	// Use the public go-sdk authplane.DPoPSigner instead of internal/crypto
	// (Gate 0).
	signer, err := authplane.NewDPoPSigner(jose.ES256)
	if err != nil {
		t.Fatalf("create DPoP signer: %v", err)
	}
	proof, err := signer.GenerateProof("POST", h.Issuer+"/oauth/token", nil)
	if err != nil {
		t.Fatalf("create DPoP proof: %v", err)
	}

	form := url.Values{
		"grant_type":         {dpopGrantTypeTokenExchange},
		"subject_token":      {userTokens.AccessToken},
		"subject_token_type": {dpopTokenTypeAccessToken},
		"client_id":          {mcpAClientID},
		"client_secret":      {mcpASecret},
		"resource":           {"mcp-1"},
		"scope":              {"tools/echo"},
	}
	req, _ := http.NewRequest("POST", h.Issuer+"/oauth/token", strings.NewReader(form.Encode()))
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	req.Header.Set("DPoP", proof)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatalf("token-exchange request: %v", err)
	}
	body, _ := io.ReadAll(resp.Body)
	resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("token-exchange (Mint dispatch + DPoP): status %d, body %s", resp.StatusCode, body)
	}
	var exchTR e2e.TokenResponse
	if err := json.Unmarshal(body, &exchTR); err != nil {
		t.Fatalf("decode exchange response: %v", err)
	}
	if exchTR.TokenType != "DPoP" {
		t.Errorf("exchanged token_type = %q, want DPoP", exchTR.TokenType)
	}

	// Introspect the exchanged token — cnf.jkt must equal the
	// thumbprint of our DPoP key.
	ir := h.IntrospectToken(exchTR.AccessToken, mcpAClientID, mcpASecret)
	if !ir.Active {
		t.Fatal("introspect: expected active=true on exchanged DPoP token")
	}
	if ir.TokenType != "DPoP" {
		t.Errorf("introspect token_type = %q, want DPoP", ir.TokenType)
	}
	expectedJKT := signer.Thumbprint()
	gotJKT, _ := ir.Cnf["jkt"].(string)
	if gotJKT != expectedJKT {
		t.Errorf("cnf.jkt = %q, want %q", gotJKT, expectedJKT)
	}

	// Issuance row carries dpop_jkt — verify via the public admin path
	//.ListForActor).
	issuances := dpopListIssuancesForActor(t, h, mcpAClientID, time.Now().Add(-1*time.Hour))
	var foundIssuance bool
	for _, iss := range issuances {
		if iss.DPoPJKT == expectedJKT && iss.BackendKind == "mint" && iss.ResourceID == mcpBRes.ID {
			foundIssuance = true
			break
		}
	}
	if !foundIssuance {
		t.Errorf("expected one Mint issuance with dpop_jkt=%q resource_id=%q for actor %s, got %d issuances", expectedJKT, mcpBRes.ID, mcpAClientID, len(issuances))
	}
}

// TestDPoP_UnifiedBrokerDispatch_JKTPersistsOnIssuance verifies that a
// DPoP proof presented to /oauth/token grant_type=token-exchange
// targeting a Broker resource:
//
//  1. Returns the upstream's access token (opaque to the AS — DPoP
//     binding cannot be expressed in the wire token because it's not a
//     JWT the AS minted).
//  2. Persists dpop_jkt on the issuances row anyway (per
//     the data model — Broker issuances record dpop_jkt for
//     forensics even though the wire token is opaque).
func TestDPoP_UnifiedBrokerDispatch_JKTPersistsOnIssuance(t *testing.T) {
	const upstreamSlug = "github-dpop"
	const email = "alice-dpop-broker@example.com"
	const password = "pass123"
	// slug and client_id are decoupled. The actor MCP's Mint
	// Resource is keyed by mcpServerSlug; the agent's auto-generated
	// client_id is bound via policy.runtime.client_ids on that Resource.
	mcpServerSlug := fmt.Sprintf("mcp-dpop-server-%d", time.Now().UnixNano())

	scopes := []string{"tools/echo"}
	h, servers := e2e.SetupE2E(t, e2e.HarnessConfig{
		EnableAdminAPI:             true,
		EnableTokenExchange:        true,
		TokenExchangeMaxChainDepth: 5,
		EnableDPoP:                 true,
		Connectors: []e2e.ConnectorConfig{
			// RefreshToken is required by the brokerproto/oauth adapter
			// (the connect dance + later refresh both go through it).
			// The mock upstream's refresh_token grant echoes the stored
			// refresh_token back as access_token, so the wire-token
			// assertion below pins the RefreshToken value, not the
			// AccessToken — same shape as agent_identity_unified_test.go
			//.
			{Service: upstreamSlug, Scopes: []string{"repo"}, AccessToken: "gho_dpop_broker", RefreshToken: "ghr_dpop_broker", ExpiresIn: 3600},
		},
	}, scopes)
	rs := servers[0]

	h.RegisterScope(rs.URI, "tools/echo", "Echo tool")
	h.CreateUser(email, password)

	webAppClientID := h.AdminCreatePublicClient("dpop-broker webapp", []string{"authorization_code"}, "tools/echo", nil)
	mcpServerClientID, mcpSecret := h.AdminCreateAgentClient("dpop-broker actor MCP", []string{dpopGrantTypeTokenExchange}, "tools/echo repo", "MCP Server as Agent")

	mcpClient := e2e.NewMCPClient(t, h, rs, webAppClientID, "http://localhost:9999/callback")
	tokens := mcpClient.FullFlow(email, password, "tools/echo", false)

	// Register the upstream broker provider + Broker resource via the
	// public admin API, then drive the /connect dance to persist the
	// BrokerGrant. Replaces the Gate-0 shortcut h.SeedConnection.
	mockBase := h.MockUpstreamURL(upstreamSlug)
	h.AdminCreateBrokerProvider(e2e.CreateBrokerProviderSpec{
		Slug:        upstreamSlug,
		DisplayName: upstreamSlug,
		Protocol:    "oauth",
		ConfigData: map[string]any{
			"client_id":         "mock-client-id",
			"client_secret_ref": "CONNECTOR_E2E_MOCK_SECRET",
			"authorize_url":     mockBase + "/authorize",
			"token_url":         mockBase + "/token",
			"response_format":   "standard",
		},
	})
	h.AdminCreateResource(e2e.CreateResourceSpec{
		Slug:               upstreamSlug,
		URI:                "https://" + upstreamSlug + ".test",
		BackendKind:        "broker",
		BrokerProviderSlug: upstreamSlug,
		DisplayName:        upstreamSlug,
		Scopes:             []e2e.AdminScope{{Name: "repo", Upstream: "repo"}},
	})
	h.RunFlowConnect(email, password, upstreamSlug)

	// register the actor MCP's Mint Resource via the admin API
	// and bind the agent client_id via policy.runtime.client_ids so
	// dispatchBroker can resolve req.ClientID back to this Resource.
	h.AdminCreateResource(e2e.CreateResourceSpec{
		Slug:        mcpServerSlug,
		URI:         "https://" + mcpServerSlug + ".test",
		BackendKind: "mint",
		DisplayName: "mcp:" + mcpServerSlug,
		Scopes:      []e2e.AdminScope{{Name: "tools/echo"}, {Name: "repo"}},
		Policy: &e2e.AdminPolicy{
			Runtime: e2e.AdminRuntimePolicy{ClientIDs: []string{mcpServerClientID}},
		},
	})
	// fronting link from the JWT-issuing Mint (mcp-0) to the
	// Broker target so dispatchFrontedBroker handles the exchange.
	h.AdminCreateFrontingLink(e2e.CreateFrontingLinkSpec{
		Source:   "mcp-0",
		Target:   upstreamSlug,
		ScopeMap: map[string][]string{"tools/echo": {"repo"}},
	})
	h.RunFlowC1Consent(email, password, webAppClientID, "http://localhost:9999/callback", mcpServerSlug, []string{"tools/echo", "repo"}, []string{"tools/echo", "repo"})

	// Build a DPoP signer and POST the token-exchange targeting the
	// Broker resource. Use the public go-sdk authplane.DPoPSigner instead of
	// internal/crypto (Gate 0).
	signer, err := authplane.NewDPoPSigner(jose.ES256)
	if err != nil {
		t.Fatalf("dpop signer: %v", err)
	}
	proof, err := signer.GenerateProof("POST", h.Issuer+"/oauth/token", nil)
	if err != nil {
		t.Fatalf("dpop proof: %v", err)
	}

	form := url.Values{
		"grant_type":         {dpopGrantTypeTokenExchange},
		"subject_token":      {tokens.AccessToken},
		"subject_token_type": {dpopTokenTypeAccessToken},
		"client_id":          {mcpServerClientID},
		"client_secret":      {mcpSecret},
		"resource":           {upstreamSlug},
		"scope":              {"repo"},
	}
	req, _ := http.NewRequest("POST", h.Issuer+"/oauth/token", strings.NewReader(form.Encode()))
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	req.Header.Set("DPoP", proof)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatalf("broker dispatch request: %v", err)
	}
	body, _ := io.ReadAll(resp.Body)
	resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("broker dispatch: status %d, body %s", resp.StatusCode, body)
	}
	var br e2e.TokenExchangeResponse
	if err := json.Unmarshal(body, &br); err != nil {
		t.Fatalf("decode broker response: %v", err)
	}
	// With the public-API path the broker adapter refreshes via
	// grant_type=refresh_token; the mock upstream echoes the stored
	// refresh_token back as the access_token. So the wire token equals
	// the connector's RefreshToken value, not its AccessToken. (Pre-
	// the SeedConnection shortcut wrote the test's expected
	// access-token string into the encrypted credential's refresh_token
	// slot, producing the same effect under a different label.)
	if br.AccessToken != "ghr_dpop_broker" {
		t.Errorf("vended token = %q, want ghr_dpop_broker (upstream credential via refresh)", br.AccessToken)
	}

	// Issuance row must carry dpop_jkt even though the wire token is
	// opaque.
	expectedJKT := signer.Thumbprint()

	// with the fronting link declared, dispatchFrontedBroker
	// substitutes the source slug ("mcp-0") for the agent's client_id
	// in the issuance row. Pre- the assertion
	// looked for the agent's client_id; the canonical fronted-dispatch
	// contract logs the gateway identity instead.
	issuances := dpopListIssuancesForActor(t, h, "mcp-0", time.Now().Add(-1*time.Hour))
	var foundIssuance bool
	for _, iss := range issuances {
		if iss.BackendKind != "broker" {
			continue
		}
		if iss.DPoPJKT == expectedJKT {
			foundIssuance = true
			break
		}
	}
	if !foundIssuance {
		// Diagnostic: show what we actually got so fronted-dispatch
		// changes don't regress silently.
		for i, iss := range issuances {
			t.Logf("issuance[%d]: backend_kind=%q client_id=%q dpop_jkt=%q resource_id=%q",
				i, iss.BackendKind, iss.ClientID, iss.DPoPJKT, iss.ResourceID)
		}
		t.Errorf("expected one Broker issuance with dpop_jkt=%q under actor mcp-0, got %d issuances", expectedJKT, len(issuances))
	}
}

// TestDPoP_UnifiedTokenExchange_NoncePathSmoke smoke-tests the
// DPoP-Nonce header on the unified token-exchange path. Two requests
// against /oauth/token grant_type=token-exchange:
//
//  1. Without a nonce → SUCCESS (harness RequireNonce=false), DPoP-Nonce
//     response header is set per RFC 9449 §8.
//  2. With the nonce returned by request 1 → SUCCESS.
//
// The existing dpop_edge_cases_test.go covers the nonce state machine
// in depth on the client_credentials path.  confirms the shape
// works on the unified token-exchange path too — different code path,
// same middleware.
func TestDPoP_UnifiedTokenExchange_NoncePathSmoke(t *testing.T) {
	scopes := []string{"tools/echo"}
	h, servers := e2e.SetupE2E(t, e2e.HarnessConfig{
		EnableAdminAPI:             true,
		EnableTokenExchange:        true,
		TokenExchangeMaxChainDepth: 5,
		EnableDPoP:                 true,
	}, scopes, scopes)
	rsA := servers[0]
	rsB := servers[1]
	h.RegisterScope(rsA.URI, "tools/echo", "Echo tool A")
	h.RegisterScope(rsB.URI, "tools/echo", "Echo tool B")

	const email = "alice-dpop-nonce@example.com"
	const password = "pass123"
	h.CreateUser(email, password)

	// client_ids are auto-generated by the AS.
	agentID := h.AdminCreatePublicClient("dpop-nonce webapp", []string{"authorization_code"}, "tools/echo", nil)
	mcpAClientID, mcpASecret := h.AdminCreateConfidentialClient("dpop-nonce actor MCP", []string{dpopGrantTypeTokenExchange}, "tools/echo")

	// Cross-client delegation: mcp-a spends the agent's consent grant.
	h.AdminAllowExchangeClient("mcp-1", mcpAClientID)

	// Drive consent through the public surface for each MCP resource
	// (replaces SeedConsentGrant + ResourceStore.GetBySlug — ).
	h.RunFlowC1Consent(email, password, agentID, "http://localhost:9999/callback", "mcp-0", []string{"tools/echo"}, []string{"tools/echo"})
	h.RunFlowC1Consent(email, password, agentID, "http://localhost:9999/callback", "mcp-1", []string{"tools/echo"}, []string{"tools/echo"})

	agentClient := e2e.NewMCPClient(t, h, rsA, agentID, "http://localhost:9999/callback")
	userTokens := agentClient.FullFlow(email, password, "tools/echo", false)

	signer, err := authplane.NewDPoPSigner(jose.ES256)
	if err != nil {
		t.Fatalf("create DPoP signer: %v", err)
	}

	// First request — no nonce, expect 200 + DPoP-Nonce header set by the
	// middleware per RFC 9449 §8.
	status1, _, nonce1 := tokenExchangeWithDPoP(t, h, userTokens.AccessToken, mcpAClientID, mcpASecret, "mcp-1", "tools/echo", signer, "")
	if status1 != http.StatusOK {
		t.Fatalf("first token-exchange + DPoP: status %d", status1)
	}
	if nonce1 == "" {
		t.Errorf("expected DPoP-Nonce header on token-exchange response (RFC 9449 §8)")
	}

	// Second request — same shape with the returned nonce. Still
	// succeeds (verifies the middleware accepts a presented nonce on
	// the unified path).
	status2, _, _ := tokenExchangeWithDPoP(t, h, userTokens.AccessToken, mcpAClientID, mcpASecret, "mcp-1", "tools/echo", signer, nonce1)
	if status2 != http.StatusOK {
		t.Fatalf("second token-exchange + DPoP (with nonce): status %d", status2)
	}
}

// tokenExchangeWithDPoP issues a token-exchange request with a fresh
// DPoP proof. Returns (status, body, dpop-nonce-response-header).
func tokenExchangeWithDPoP(
	t *testing.T,
	h *e2e.TestHarness,
	subjectToken, clientID, clientSecret, resourceSlug, scope string,
	signer *authplane.DPoPSigner,
	nonce string,
) (int, []byte, string) {
	t.Helper()
	var opts *authplane.DPoPProofOptions
	if nonce != "" {
		opts = &authplane.DPoPProofOptions{Nonce: nonce}
	}
	proof, err := signer.GenerateProof("POST", h.Issuer+"/oauth/token", opts)
	if err != nil {
		t.Fatalf("create DPoP proof: %v", err)
	}

	form := url.Values{
		"grant_type":         {dpopGrantTypeTokenExchange},
		"subject_token":      {subjectToken},
		"subject_token_type": {dpopTokenTypeAccessToken},
		"client_id":          {clientID},
		"client_secret":      {clientSecret},
		"resource":           {resourceSlug},
		"scope":              {scope},
	}
	req, _ := http.NewRequest("POST", h.Issuer+"/oauth/token", strings.NewReader(form.Encode()))
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	req.Header.Set("DPoP", proof)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatalf("token-exchange + DPoP request: %v", err)
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(resp.Body)
	return resp.StatusCode, body, resp.Header.Get("DPoP-Nonce")
}

// dpopAdminIssuanceView mirrors the subset of internal/admin/dto.IssuanceView
// the DPoP unified-dispatch tests actually read. Defined locally so the
// test does not import internal/admin/dto (Gate 0).
type dpopAdminIssuanceView struct {
	ID          string   `json:"id"`
	ClientID    string   `json:"client_id"`
	ResourceID  string   `json:"resource_id"`
	AgentID     string   `json:"agent_id"`
	BackendKind string   `json:"backend_kind"`
	Scopes      []string `json:"scopes"`
	DPoPJKT     string   `json:"dpop_jkt,omitempty"`
}

// dpopListIssuancesForActor calls
// GET /admin/issuances?client=<id>&since=<rfc3339> and returns the
// parsed issuance rows. Replaces the Gate-0 shortcut
// h.IssuanceStore().ListForActor with the public admin path.
func dpopListIssuancesForActor(t *testing.T, h *e2e.TestHarness, actorClientID string, since time.Time) []dpopAdminIssuanceView {
	t.Helper()
	path := fmt.Sprintf("/admin/issuances?client=%s&since=%s", actorClientID, since.UTC().Format(time.RFC3339))
	resp := h.AdminRequest("GET", path, nil)
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("GET %s: status %d", path, resp.StatusCode)
	}
	var body struct {
		Issuances []dpopAdminIssuanceView `json:"issuances"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&body); err != nil {
		t.Fatalf("decode admin issuances response: %v", err)
	}
	return body.Issuances
}
