//go:build e2e

package scenarios

import (
	"encoding/json"
	"io"
	"net/http"
	"reflect"
	"sort"
	"testing"

	"github.com/authplane/authserver/e2e"
)

// TestFrontingAdmin_CRUD exercises the full POST/GET/PATCH/GET/DELETE
// round-trip on /admin/fronting through the public admin HTTP surface
// (no internal/* imports, no store accessors). Two distinct properties
// are pinned:
//
//  1. Wire-shape: every operation returns the / view shape
//     (source_slug/target_slug/scope_map/created_at/created_by). The
//     POST request body uses the abbreviated source/target field names;
//     the response always uses the suffixed *_slug names. The drift
//
// between request and response shapes is intentional (per
//
//	   review notes) so this test pins it.
//
//	2. Runtime impact: the fronted-path runtime consults the same
//	   fronting_links rows admin writes, so DELETE here must collapse
//	   the next /oauth/token exchange back onto the direct path. The
//	   direct path's consent gate fires (consent_required) because no
//	   consent_grants row was ever recorded for the gateway client at
//	   the rest-api resource — this matches the merge-gate test (Task C)
//	   no-link branch and proves admin and runtime stay in sync without
//	   any cache invalidation step.
//
// Audit assertion mirrors auditDetailContainsAll from the merge-gate
// test: poll GET /admin/audit?action=<action> and look for the row by
// source/target needle. We expect at least one row each for created,
// patched, deleted.
func TestFrontingAdmin_CRUD(t *testing.T) {
	const (
		gwSlug  = "fc-mcp-gw"
		apiSlug = "fc-rest-api"
		gwURI   = "https://fc-mcp-gw.test"
		apiURI  = "https://fc-rest-api.test"

		gwRedirect = "http://localhost:9999/callback"

		email    = "alice-frontingcrud@example.com"
		password = "pass123"
	)

	h, _ := e2e.SetupE2E(t, e2e.HarnessConfig{
		EnableAdminAPI:             true,
		EnableTokenExchange:        true,
		TokenExchangeMaxChainDepth: 5,
	}, []string{"placeholder"})

	h.CreateUser(email, password)

	// Clients first — AdminCreateResource validates allowed_client_ids.
	// client_ids are auto-generated by the AS.
	gwClient := h.AdminCreatePublicClient(
		"fronting-CRUD gateway",
		[]string{"authorization_code"},
		"A B C",
		[]string{gwRedirect},
	)
	agentClient, agentSecret := h.AdminCreateAgentClient(
		" fronting CRUD agent",
		[]string{"urn:ietf:params:oauth:grant-type:token-exchange"},
		"AA BB CC",
		" fronting CRUD agent",
	)

	// Source + target Mint resources.
	h.AdminCreateResource(e2e.CreateResourceSpec{
		Slug:        gwSlug,
		URI:         gwURI,
		BackendKind: "mint",
		DisplayName: "MCP Gateway (CRUD test)",
		Scopes: []e2e.AdminScope{
			{Name: "A"}, {Name: "B"}, {Name: "C"},
		},
	})
	h.AdminCreateResource(e2e.CreateResourceSpec{
		Slug:        apiSlug,
		URI:         apiURI,
		BackendKind: "mint",
		DisplayName: "REST API (CRUD test)",
		Scopes: []e2e.AdminScope{
			{Name: "AA"}, {Name: "BB"}, {Name: "CC"},
		},
		Policy: &e2e.AdminPolicy{
			Exchange: e2e.AdminExchangePolicy{
				AllowedClientIDs: []string{agentClient},
			},
		},
	})

	// --- 1. POST /admin/fronting --------------------------------------
	postBody := map[string]any{
		"source":    gwSlug,
		"target":    apiSlug,
		"scope_map": map[string][]string{"A": {"AA"}},
	}
	createdView := decodeFrontingLinkView(t, h.AdminRequest("POST", "/admin/fronting", postBody), http.StatusCreated)
	if createdView.SourceSlug != gwSlug {
		t.Errorf("POST source_slug = %q, want %q", createdView.SourceSlug, gwSlug)
	}
	if createdView.TargetSlug != apiSlug {
		t.Errorf("POST target_slug = %q, want %q", createdView.TargetSlug, apiSlug)
	}
	if got := mappedTargets(createdView.ScopeMap, "A"); !reflect.DeepEqual(got, []string{"AA"}) {
		t.Errorf("POST scope_map[A] = %v, want [AA]", got)
	}
	if createdView.CreatedAt == "" {
		t.Errorf("POST: created_at empty, expected RFC3339 timestamp")
	}
	if createdView.CreatedBy == "" {
		t.Errorf("POST: created_by empty, expected actor id")
	}

	// --- 2. GET /admin/fronting/{source}/{target} ---------------------
	getView := decodeFrontingLinkView(t, h.AdminRequest("GET", "/admin/fronting/"+gwSlug+"/"+apiSlug, nil), http.StatusOK)
	if getView.SourceSlug != gwSlug || getView.TargetSlug != apiSlug {
		t.Errorf("GET round-trip mismatch: got source=%q target=%q, want %q %q",
			getView.SourceSlug, getView.TargetSlug, gwSlug, apiSlug)
	}
	if got := mappedTargets(getView.ScopeMap, "A"); !reflect.DeepEqual(got, []string{"AA"}) {
		t.Errorf("GET scope_map[A] = %v, want [AA]", got)
	}
	if getView.CreatedAt != createdView.CreatedAt {
		t.Errorf("GET created_at = %q, want POST-returned %q", getView.CreatedAt, createdView.CreatedAt)
	}

	// --- 3. PATCH /admin/fronting/{source}/{target} -------------------
	patchBody := map[string]any{
		"scope_map": map[string][]string{
			"A": {"AA"},
			"B": {"BB"},
		},
	}
	patchedView := decodeFrontingLinkView(t, h.AdminRequest("PATCH", "/admin/fronting/"+gwSlug+"/"+apiSlug, patchBody), http.StatusOK)
	if patchedView.SourceSlug != gwSlug || patchedView.TargetSlug != apiSlug {
		t.Errorf("PATCH source/target drift: got %q/%q", patchedView.SourceSlug, patchedView.TargetSlug)
	}
	if got := mappedTargets(patchedView.ScopeMap, "B"); !reflect.DeepEqual(got, []string{"BB"}) {
		t.Errorf("PATCH scope_map[B] = %v, want [BB] (the new mapping)", got)
	}
	if got := mappedTargets(patchedView.ScopeMap, "A"); !reflect.DeepEqual(got, []string{"AA"}) {
		t.Errorf("PATCH scope_map[A] = %v, want [AA] (preserved across patch)", got)
	}

	// GET again — confirms PATCH persisted, not just echoed.
	postPatchGet := decodeFrontingLinkView(t, h.AdminRequest("GET", "/admin/fronting/"+gwSlug+"/"+apiSlug, nil), http.StatusOK)
	gotKeys := scopeMapKeys(postPatchGet.ScopeMap)
	wantKeys := []string{"A", "B"}
	if !reflect.DeepEqual(gotKeys, wantKeys) {
		t.Errorf("GET after PATCH: scope_map keys = %v, want %v (PATCH should have persisted)", gotKeys, wantKeys)
	}

	// --- 4. Runtime sync: link present -> fronted exchange succeeds ---
	// Drive PKCE at the GW so we have a subject_token to exchange. The
	// authorize / consent dance writes a consent_grants row scoped to the
	// gateway resource only; it does NOT cover the rest-api, which is
	// the load-bearing precondition for the post-DELETE consent_required
	// branch below.
	code, verifier, _ := h.RunFlowC1Consent(
		email, password, gwClient, gwRedirect, gwSlug,
		[]string{"A", "B"},
		[]string{"A", "B"},
	)
	if code == "" {
		t.Fatal("RunFlowC1Consent returned empty code")
	}
	gwTokens := h.ExchangeCode(code, verifier, gwClient, gwRedirect)
	if gwTokens.AccessToken == "" {
		t.Fatal("expected GW access token from auth-code flow")
	}

	exch := h.TokenExchangeWithResource(
		agentClient, agentSecret,
		gwTokens.AccessToken,
		"urn:ietf:params:oauth:token-type:access_token",
		"AA BB",
		apiSlug,
	)
	if exch.AccessToken == "" {
		t.Fatal("fronted exchange (link present) returned empty access_token")
	}

	// --- 5. DELETE /admin/fronting/{source}/{target} ------------------
	delResp := h.AdminRequest("DELETE", "/admin/fronting/"+gwSlug+"/"+apiSlug, nil)
	defer delResp.Body.Close()
	// wire format: 204 No Content. Be tolerant of 200 in case a
	// future server adds a JSON receipt body, but reject anything else.
	if delResp.StatusCode != http.StatusNoContent && delResp.StatusCode != http.StatusOK {
		raw, _ := io.ReadAll(delResp.Body)
		t.Fatalf("DELETE: status %d, want 204; body=%s", delResp.StatusCode, string(raw))
	}

	// --- 6. GET after DELETE -> 404 -----------------------------------
	getAfterDel := h.AdminRequest("GET", "/admin/fronting/"+gwSlug+"/"+apiSlug, nil)
	getAfterDel.Body.Close()
	if getAfterDel.StatusCode != http.StatusNotFound {
		t.Errorf("GET after DELETE: status = %d, want 404", getAfterDel.StatusCode)
	}

	// --- 7. Runtime sync: link gone -> invalid_scope ------------------
	// Same exchange call, same subject token, same agent — only the
	// fronting_links row changed. The fronted path no longer matches
	// (no link), so we fall through to direct dispatch. Under ADR-002's
	// hybrid subject-scope ceiling (commit c1f66e2) the direct path
	// rejects with invalid_scope BEFORE the consent gate fires because
	// the subject token's source-namespace scopes ("A B") cannot cover
	// the requested target-namespace scopes ("AA BB") without an
	// operator-declared scope_map. The semantic is "no policy exists to
	// bridge these namespaces" — consent alone would not unblock it.
	// This is still the runtime-stays-in-sync proof: admin DELETE is
	// observable on the very next /oauth/token call.
	denied := h.TokenExchangeWithResourceExpectError(
		agentClient, agentSecret,
		gwTokens.AccessToken,
		"urn:ietf:params:oauth:token-type:access_token",
		"AA BB",
		apiSlug,
	)
	if denied.Error != "invalid_scope" {
		t.Errorf("post-DELETE exchange: error = %q, want invalid_scope (ADR-002 hybrid ceiling fires before consent on direct path)", denied.Error)
	}
	if denied.Error == "consent_required" {
		t.Error("post-DELETE direct path leaked consent_required — ceiling regression (ADR-002)")
	}

	// --- 8. Audit trail -----------------------------------------------
	// Each operation records its own audit row with a recognisable
	// detail string. We assert presence of all three by source/target
	// needle, mirroring the merge-gate test's auditDetailContainsAll
	// helper rather than introducing a new harness method.
	srcTgt := "source=" + gwSlug + " target=" + apiSlug
	if !auditDetailContainsAll(t, h, "fronting_link.created", srcTgt) {
		t.Errorf("expected fronting_link.created audit row with %q", srcTgt)
	}
	if !auditDetailContainsAll(t, h, "fronting_link.patched", srcTgt) {
		t.Errorf("expected fronting_link.patched audit row with %q", srcTgt)
	}
	if !auditDetailContainsAll(t, h, "fronting_link.deleted", srcTgt) {
		t.Errorf("expected fronting_link.deleted audit row with %q", srcTgt)
	}
}

// frontingLinkView mirrors the wire shape of dto.FrontingLinkView so the
// e2e test can assert the public field names without importing
// internal/admin/dto (the harness rule of thumb).
type frontingLinkView struct {
	SourceSlug string              `json:"source_slug"`
	TargetSlug string              `json:"target_slug"`
	ScopeMap   map[string][]string `json:"scope_map"`
	CreatedAt  string              `json:"created_at"`
	CreatedBy  string              `json:"created_by"`
}

// decodeFrontingLinkView reads resp into a frontingLinkView and asserts
// the status code. Closes resp.Body. Centralised so each call site stays
// a single-liner — the verbose decode+status pattern was getting copied
// six times in the parent test.
func decodeFrontingLinkView(t *testing.T, resp *http.Response, wantStatus int) frontingLinkView {
	t.Helper()
	defer resp.Body.Close()
	if resp.StatusCode != wantStatus {
		raw, _ := io.ReadAll(resp.Body)
		t.Fatalf("status = %d, want %d; body=%s", resp.StatusCode, wantStatus, string(raw))
	}
	var view frontingLinkView
	if err := json.NewDecoder(resp.Body).Decode(&view); err != nil {
		t.Fatalf("decode fronting link view: %v", err)
	}
	return view
}

// mappedTargets returns scope_map[src] sorted, or nil on miss.
func mappedTargets(sm map[string][]string, src string) []string {
	v, ok := sm[src]
	if !ok {
		return nil
	}
	out := append([]string{}, v...)
	sort.Strings(out)
	return out
}

// scopeMapKeys returns the sorted keys of sm so map ordering doesn't
// flake the assertion.
func scopeMapKeys(sm map[string][]string) []string {
	out := make([]string, 0, len(sm))
	for k := range sm {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
