//go:build e2e

package scenarios

import (
	"encoding/json"
	"net/http"
	"reflect"
	"sort"
	"strings"
	"testing"

	"github.com/authplane/authserver/e2e"
)

// TestGatewayFanout_MintToMint is the merge gate. PR is rejected
// if this scenario does not pass.
//
// Verifies the Mint->Mint fronted-exchange path end-to-end through the
// public admin + /authorize + /oauth/token surfaces:
//
//  1. Two Mint resources (mcp-gw + rest-api) are registered, plus a
//     fronting link that maps source-side scopes A,B onto target-side
//     scopes AA,BB.
//  2. The user drives PKCE at /authorize for resource=mcp-gw with
//     scope=[A B] and consents — this issues the GW token.
//  3. The agent (agent-fanout) calls /oauth/token with grant_type=
//     token-exchange, subject_token=<GW token>, resource=rest-api,
//     scope="AA BB".
//  4. The issued token follows the Option β claim shape
//
// : aud=rest-api URI, sub=user, scope="AA BB",
//
//	   client_id=mcp-gw (the source slug — NOT the agent),
//	   act.sub=mcp-gw, act.act.sub=<agent client_id>.
//	5. Audit row carries chain_kind=fronted and via_link=mcp-gw->rest-api
//	   (ASCII arrow, NOT unicode arrow).
//	6. Negative — same exchange WITHOUT the link -> 400 invalid_scope.
//	   ADR-002 (hybrid subject-scope ceiling, commit c1f66e2) makes the
//	   direct path fail-closed when the subject token's scope namespace
//	   (source-resource scopes "A B") does not cover the requested target
//	   scopes ("AA BB"). The ceiling fires BEFORE the consent gate because
//	   even with a consent_grants row the exchange would still be invalid
//	   until an operator declares a fronting link to translate namespaces.
//	   This is the merge-gate contract — see CHANGELOG entry "token-
//	   exchange: hybrid subject-scope ceiling tightens no-link error to
//	   invalid_scope" for migration notes.
//	7. Negative — link present but the GW token is missing the source-side
//	   scope a target-side request maps onto -> 400 invalid_scope (no
//
// consent_required fallback on the fronted path; Task B
//
//	pinned this).
func TestGatewayFanout_MintToMint(t *testing.T) {
	const (
		gwSlug  = "mcp-gw"
		apiSlug = "rest-api"
		gwURI   = "https://mcp-gw.test"
		apiURI  = "https://rest-api.test"

		gwRedirect = "http://localhost:9999/callback"

		email    = "alice-fanout@example.com"
		password = "pass123"
	)

	// SetupE2E requires at least one MCP resource server per the
	// two-phase config. The placeholder server is unused — both
	// fronting endpoints (gw + api) are registered through
	// AdminCreateResource below.
	h, _ := e2e.SetupE2E(t, e2e.HarnessConfig{
		EnableAdminAPI:             true,
		EnableTokenExchange:        true,
		TokenExchangeMaxChainDepth: 5,
	}, []string{"placeholder"})

	h.CreateUser(email, password)

	// Clients are created before the target resource because
	// AdminCreateResource validates that every client_id named in
	// policy.exchange.allowed_client_ids already exists. client_ids
	// are auto-generated by the AS and cannot be set by operators or tests
	// — the public surface (POST /admin/clients) is the only path.
	gwClient := h.AdminCreatePublicClient(
		"MCP Gateway",
		[]string{"authorization_code"},
		"A B C",
		[]string{gwRedirect},
	)

	// The fanout agent. Confidential client with the token-exchange
	// grant; flagged IsAgent so the agent identity wiring picks it up.
	agentClient, agentSecret := h.AdminCreateAgentClient(
		" fanout agent",
		[]string{"urn:ietf:params:oauth:grant-type:token-exchange"},
		"AA BB CC",
		" fanout agent",
	)

	// Source: mcp-gw — gateway resource the user authenticates at via
	// PKCE. Catalog [A B C]; the test only ever requests [A B].
	h.AdminCreateResource(e2e.CreateResourceSpec{
		Slug:        gwSlug,
		URI:         gwURI,
		BackendKind: "mint",
		DisplayName: "MCP Gateway",
		Scopes: []e2e.AdminScope{
			{Name: "A"}, {Name: "B"}, {Name: "C"},
		},
	})

	// Target: rest-api — what the agent fans out to. Catalog [AA BB CC].
	// agent-fanout must be on the operator allowlist for the fronted
	// dispatch to clear the operator gate inside dispatchMint.
	h.AdminCreateResource(e2e.CreateResourceSpec{
		Slug:        apiSlug,
		URI:         apiURI,
		BackendKind: "mint",
		DisplayName: "REST API",
		Scopes: []e2e.AdminScope{
			{Name: "AA"}, {Name: "BB"}, {Name: "CC"},
		},
		Policy: &e2e.AdminPolicy{
			Exchange: e2e.AdminExchangePolicy{
				AllowedClientIDs: []string{agentClient},
			},
		},
	})

	// The fronting link operator declaration. Both source-side scopes
	// each map to the matching target-side scope; CC is intentionally
	// left out so any test that asks for CC trips the unmapped-target
	// branch (we don't exercise that path here — Task B unit
	// tests pin it).
	h.AdminCreateFrontingLink(e2e.CreateFrontingLinkSpec{
		Source:   gwSlug,
		Target:   apiSlug,
		ScopeMap: map[string][]string{"A": {"AA"}, "B": {"BB"}},
	})

	// --- 1. PKCE at the gateway -> user consents -> GW token. ---
	code, verifier, _ := h.RunFlowC1Consent(
		email, password, gwClient, gwRedirect, gwSlug,
		[]string{"A", "B"},
		[]string{"A", "B"},
	)
	if code == "" {
		t.Fatal("RunFlowC1Consent at gateway returned empty code")
	}
	gwTokens := h.ExchangeCode(code, verifier, gwClient, gwRedirect)
	if gwTokens.AccessToken == "" {
		t.Fatal("expected GW access token from auth-code flow")
	}

	// Sanity: the GW token must carry aud=<gw URI> so resolveSourceForFronting
	// can walk the audience and find the mcp-gw resource.
	gwClaims := parseJWTClaims(t, gwTokens.AccessToken)
	if got := audAsString(gwClaims["aud"]); got != gwURI {
		t.Fatalf("GW token aud = %q, want %q (fronting source resolution walks aud)", got, gwURI)
	}

	// --- 2. Fronted exchange. ---
	exch := h.TokenExchangeWithResource(
		agentClient, agentSecret,
		gwTokens.AccessToken,
		"urn:ietf:params:oauth:token-type:access_token",
		"AA BB",
		apiSlug,
	)
	if exch.AccessToken == "" {
		t.Fatal("fronted token exchange returned empty access token")
	}

	// Wire-shape assertion (Option β).
	claims := parseJWTClaims(t, exch.AccessToken)
	if got, _ := claims["sub"].(string); got != "" {
		// sub is the user's id; can't predict without lookup, just confirm
		// it's non-empty AND not the agent or the source slug (i.e. user-
		// shaped, not client-shaped).
		if got == agentClient || got == gwSlug {
			t.Errorf("issued token sub = %q, want user id (Option β preserves user subject)", got)
		}
	} else {
		t.Errorf("issued token has empty sub")
	}
	if got := audAsString(claims["aud"]); got != apiURI {
		t.Errorf("aud = %q, want %q (target URI)", got, apiURI)
	}
	gotScopes := strings.Fields(stringClaim(claims, "scope"))
	sort.Strings(gotScopes)
	if !reflect.DeepEqual(gotScopes, []string{"AA", "BB"}) {
		t.Errorf("scope = %v, want [AA BB]", gotScopes)
	}
	if got, _ := claims["client_id"].(string); got != gwSlug {
		t.Errorf("client_id = %q, want %q (Option β: source slug, NOT the agent)", got, gwSlug)
	}
	act, _ := claims["act"].(map[string]any)
	if act == nil {
		t.Fatal("act claim missing on fronted token (Option β requires source at depth 1)")
	}
	if got, _ := act["sub"].(string); got != gwSlug {
		t.Errorf("act.sub = %q, want %q (Option β outer hop)", got, gwSlug)
	}
	innerAct, _ := act["act"].(map[string]any)
	if innerAct == nil {
		t.Fatal("act.act missing — agent should be at depth 2 under Option β")
	}
	if got, _ := innerAct["sub"].(string); got != agentClient {
		t.Errorf("act.act.sub = %q, want %q (the agent at depth 2)", got, agentClient)
	}

	// --- 3. Audit row carries chain_kind + via_link (ASCII arrow). ---
	wantViaLink := gwSlug + "->" + apiSlug
	if !auditDetailContainsAll(t, h, "token.exchanged", "chain_kind=fronted", "via_link="+wantViaLink) {
		t.Errorf("expected an audit row with chain_kind=fronted and via_link=%s", wantViaLink)
	}

	// --- 4. Negative path #1: NO link -> invalid_scope. ---
	//
	// Pre-ADR-002 this returned consent_required because the direct path
	// fell through to the consent gate. ADR-002 added the hybrid subject-
	// scope ceiling (services/token_exchange.go:947, enforceSubjectScopeCeiling),
	// which fires BEFORE the consent gate. The ceiling sees that the subject
	// token's scope "A B" does not contain the requested "AA BB" — the
	// scopes live in different namespaces (source vs target), and without
	// a fronting link the AS has no operator-declared translation. The
	// answer is invalid_scope (no policy exists to bridge namespaces),
	// not consent_required (consent alone would not unblock the call).
	// A regression to consent_required would be a hardening loss.
	h.AdminDeleteFrontingLink(gwSlug, apiSlug)

	deniedNoLink := h.TokenExchangeWithResourceExpectError(
		agentClient, agentSecret,
		gwTokens.AccessToken,
		"urn:ietf:params:oauth:token-type:access_token",
		"AA BB",
		apiSlug,
	)
	if deniedNoLink.Error != "invalid_scope" {
		t.Errorf("no-link exchange: error = %q, want invalid_scope (ADR-002 hybrid ceiling fires before consent)", deniedNoLink.Error)
	}
	if deniedNoLink.Error == "consent_required" {
		t.Error("no-link direct path leaked consent_required — ceiling regression (ADR-002)")
	}

	// --- 5. Negative path #2: link present but subject token missing
	// the source-side scope a requested target-side scope maps onto.
	// Recreate the link, drive PKCE for [A] only, then exchange for
	// "BB" (which needs source-side B). Expect invalid_scope, NOT
	// consent_required (the fronted path must not degrade).
	h.AdminCreateFrontingLink(e2e.CreateFrontingLinkSpec{
		Source:   gwSlug,
		Target:   apiSlug,
		ScopeMap: map[string][]string{"A": {"AA"}, "B": {"BB"}},
	})

	const narrowEmail = "alice-narrow-fanout@example.com"
	h.CreateUser(narrowEmail, password)
	narrowCode, narrowVerifier, _ := h.RunFlowC1Consent(
		narrowEmail, password, gwClient, gwRedirect, gwSlug,
		[]string{"A"}, // requested narrow
		[]string{"A"}, // approved narrow
	)
	if narrowCode == "" {
		t.Fatal("RunFlowC1Consent (narrow) returned empty code")
	}
	narrowTokens := h.ExchangeCode(narrowCode, narrowVerifier, gwClient, gwRedirect)
	if narrowTokens.AccessToken == "" {
		t.Fatal("narrow auth-code redemption returned empty access token")
	}

	deniedMissingSrc := h.TokenExchangeWithResourceExpectError(
		agentClient, agentSecret,
		narrowTokens.AccessToken,
		"urn:ietf:params:oauth:token-type:access_token",
		"BB",
		apiSlug,
	)
	if deniedMissingSrc.Error != "invalid_scope" {
		t.Errorf("missing-source-scope exchange: error = %q, want invalid_scope (fronted path must not fall back to consent_required)", deniedMissingSrc.Error)
	}
	if deniedMissingSrc.Error == "consent_required" {
		t.Error("fronted path leaked consent_required on missing source scope — the dispatchMint regression guard failed")
	}
}

// audAsString normalises the JWT 'aud' claim to a single string. RFC 7519
// allows aud to be either a string or array; the AS emits []string with
// exactly one element for these tokens.
func audAsString(raw any) string {
	switch v := raw.(type) {
	case string:
		return v
	case []any:
		if len(v) == 0 {
			return ""
		}
		s, _ := v[0].(string)
		return s
	}
	return ""
}

// stringClaim returns claims[key] coerced to string, or "" on miss/type-mismatch.
func stringClaim(claims map[string]any, key string) string {
	s, _ := claims[key].(string)
	return s
}

// auditDetailContainsAll polls GET /admin/audit?action=<action> for the
// most recent N rows and returns true iff at least one row's Detail
// contains every needle. Used to assert chain_kind + via_link on the
// fronted-path token.exchanged row.
func auditDetailContainsAll(t *testing.T, h *e2e.TestHarness, action string, needles ...string) bool {
	t.Helper()
	resp := h.AdminRequest("GET", "/admin/audit?action="+action+"&limit=50", nil)
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("GET /admin/audit?action=%s: status %d", action, resp.StatusCode)
	}
	var rows []struct {
		Action string `json:"action"`
		Detail string `json:"detail"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&rows); err != nil {
		t.Fatalf("decode audit response: %v", err)
	}
	for _, row := range rows {
		hits := 0
		for _, n := range needles {
			if strings.Contains(row.Detail, n) {
				hits++
			}
		}
		if hits == len(needles) {
			return true
		}
	}
	return false
}
