//go:build e2e

package scenarios

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"testing"
	"time"

	"github.com/authplane/authserver/e2e"
)

// TestUnifiedAdminSurface_FullLifecycle covers
// end-to-end via the unified admin HTTP endpoints:
//
//   - POST /admin/broker-providers          ( create)
//   - POST /admin/resources                 ( create — broker kind)
//   - GET  /admin/resources?backend_kind=…  ( filter)
//   - POST /oauth/token grant_type=…        ( dispatch over the
//     admin-created provider+resource)
//   - GET  /admin/issuances?user=…          ( forensics)
//   - DELETE /admin/grants/broker/{id}      ( admin revocation)
//   - GET  /admin/audit?action=…            ( audit pipeline —
//     all nine new action constants exercised)
//
// Plus the foreign-key + bad-protocol negative cases.
//
// migration: every internal/ import + every harness
// Seed*/*Store() shortcut has been replaced with a public-API path.
// BrokerGrants come from RunFlowConnect (the /connect dance against the
// in-process mock upstream); the actor MCP's Mint resource +
// consent_grants row come from AdminCreateResource + RunFlowC1Consent;
// the cross-tuple defense-in-depth check at the end reads the admin
// /admin/users/{id}/grants endpoint instead of the consentGrantStore.
// The audit-action constants are inlined as their wire-format string
// values (mirroring internal/domain/audit/entity.go) so the test does
// not need to import the audit package.
func TestUnifiedAdminSurface_FullLifecycle(t *testing.T) {
	// client_ids are auto-generated by the AS at registration
	// time. The Mint Resource backing the actor MCP is keyed by a
	// separate slug; the agent's client_id is bound via
	// policy.runtime.client_ids on that Resource.
	nano := time.Now().UnixNano()
	mcpResourceSlug := fmt.Sprintf("mcp-server-%d", nano)

	scopes := []string{"tools/echo"}
	h, servers := e2e.SetupE2E(t, e2e.HarnessConfig{
		EnableAdminAPI:             true,
		EnableTokenExchange:        true,
		TokenExchangeMaxChainDepth: 5,
		Connectors: []e2e.ConnectorConfig{
			// RefreshToken intentionally set to "gho_unified_admin"
			// (the value the test asserts comes back from the broker
			// dispatch). Pre-, SeedBrokerGrant directly persisted
			// "gho_unified_admin" as the credential and the mock's
			// refresh-token grant echoed it back. Since RunFlowConnect
			// drives the public /connect dance, the credential persisted
			// is whatever RefreshToken the connector returns; setting it
			// to "gho_unified_admin" preserves the original assertion's
			// intent (the user-controlled seed flows through the broker
			// pipeline unchanged).
			{Service: "github", Scopes: []string{"repo"}, AccessToken: "gho_unified_admin", RefreshToken: "gho_unified_admin", ExpiresIn: 3600},
		},
	}, scopes)
	rs := servers[0]

	h.RegisterScope(rs.URI, "tools/echo", "Echo tool")
	const userEmail = "unified-admin@example.com"
	const userPassword = "pass123"
	userID := h.CreateUser(userEmail, userPassword)

	mockBase := h.MockUpstreamURL("github")
	if mockBase == "" {
		t.Fatal("mock upstream URL for slug 'github' missing — connector config dropped?")
	}

	// Pre-seed the MCP + agent clients so the resource policy
	// allowlist can reference the MCP id at create time. The
	// ResourceAdminService validates allowed_client_ids against the
	// client store.
	webAppClientID := h.AdminCreatePublicClient("unified-admin webapp", []string{"authorization_code"}, "tools/echo", nil)
	// token.GrantTypeTokenExchange inlined as its RFC 8693 URN
	// to drop the internal/domain/token import.
	mcpServerClientID, mcpSecret := h.AdminCreateConfidentialClient("unified-admin mcp",
		[]string{"urn:ietf:params:oauth:grant-type:token-exchange"}, "tools/echo")

	// --- 1. Admin creates a BrokerProvider via the unified surface.
	// config_data wires the in-process mock upstream (same shape
	// SeedConnection emits internally so the brokerproto/oauth adapter
	// can reach the token endpoint on a refresh_token exchange).
	bpResp := h.AdminRequest("POST", "/admin/broker-providers", map[string]any{
		"slug":         "github-unified",
		"display_name": "GitHub (unified)",
		"protocol":     "oauth",
		"config_data": map[string]any{
			"client_id":         "mock-client-id",
			"client_secret_ref": "CONNECTOR_E2E_MOCK_SECRET",
			"authorize_url":     mockBase + "/authorize",
			"token_url":         mockBase + "/token",
			"response_format":   "standard",
		},
	})
	defer bpResp.Body.Close()
	if bpResp.StatusCode != http.StatusCreated {
		body, _ := io.ReadAll(bpResp.Body)
		t.Fatalf("create broker provider: %d %s", bpResp.StatusCode, body)
	}
	var bp map[string]any
	if err := json.NewDecoder(bpResp.Body).Decode(&bp); err != nil {
		t.Fatalf("decode broker provider response: %v", err)
	}
	bpID, _ := bp["id"].(string)
	if bpID == "" {
		t.Fatal("created broker provider missing id")
	}

	// --- 2. Admin creates a Broker Resource referencing it.
	resResp := h.AdminRequest("POST", "/admin/resources", map[string]any{
		"slug":               "github-unified-repo",
		"uri":                "https://api.github.com/repos",
		"backend_kind":       "broker",
		"broker_provider_id": bpID,
		"display_name":       "GitHub Repos",
		"scopes": []map[string]any{
			{"name": "repo", "upstream": "repo"},
		},
		"policy": map[string]any{
			"exchange": map[string]any{"allowed_client_ids": []string{mcpServerClientID}},
			"connect":  map[string]any{"allowed_return_urls": []string{}},
		},
	})
	defer resResp.Body.Close()
	if resResp.StatusCode != http.StatusCreated {
		body, _ := io.ReadAll(resResp.Body)
		t.Fatalf("create broker resource: %d %s", resResp.StatusCode, body)
	}
	var brokerResource map[string]any
	if err := json.NewDecoder(resResp.Body).Decode(&brokerResource); err != nil {
		t.Fatalf("decode resource: %v", err)
	}
	brokerResourceID, _ := brokerResource["id"].(string)

	// --- 2b. register the actor MCP's Mint resource via the
	// admin API. Replaces the resourceStore.Create the old
	// SeedAgentAttestation shortcut performed. Created once here so
	// later RunFlowC1Consent calls (which only need the resource to
	// already exist for the consent flow's resource resolution) can be
	// idempotent.
	//
	// The URI is a placeholder absolute URL — the admin API requires
	// http/https schemes (validateResourceURI in
	// internal/domain/resource/resource.go) and the consent service
	// stores this URI on the session so GrantConsent can resolve the
	// resource for the consent_grants Upsert. Without a non-empty URI
	// the consent grant is silently skipped (consent.go::GrantConsent —
	// `if resolved != nil { Upsert(...) }`).
	mcpResourceURI := "https://mcp.test/" + mcpResourceSlug
	h.AdminCreateResource(e2e.CreateResourceSpec{
		Slug:        mcpResourceSlug,
		URI:         mcpResourceURI,
		BackendKind: "mint",
		DisplayName: "mcp:" + mcpResourceSlug,
		Scopes: []e2e.AdminScope{
			{Name: "tools/echo"},
			{Name: "repo"},
		},
		Policy: &e2e.AdminPolicy{
			Runtime: e2e.AdminRuntimePolicy{ClientIDs: []string{mcpServerClientID}},
		},
	})

	// the subject token issued by mcpClient.FullFlow has
	// aud=mcp-0 (the SetupE2E placeholder Mint resource), and the
	// token-exchange below targets github-unified-repo (a Broker). The
	// non-fronted Mint→Broker dispatch path is no longer permitted —
	// dispatchBroker now returns FrontingLinkMissingError unless a
	// fronting_links row connects them. Declare the link so this test
	// exercises the canonical fronted-broker dispatch.
	h.AdminCreateFrontingLink(e2e.CreateFrontingLinkSpec{
		Source: "mcp-0", // SetupE2E names the first resource server "mcp-0"
		Target: "github-unified-repo",
		ScopeMap: map[string][]string{
			"tools/echo": {"repo"},
		},
	})

	// --- 3. Filter sub-test: ?backend_kind=broker returns at least the
	// resource we just created.
	t.Run("ListFiltersByBackendKind", func(t *testing.T) {
		listResp := h.AdminRequest("GET", "/admin/resources?backend_kind=broker", nil)
		defer listResp.Body.Close()
		if listResp.StatusCode != http.StatusOK {
			t.Fatalf("list status: %d", listResp.StatusCode)
		}
		var rows []map[string]any
		if err := json.NewDecoder(listResp.Body).Decode(&rows); err != nil {
			t.Fatalf("decode list: %v", err)
		}
		var found bool
		for _, r := range rows {
			if r["backend_kind"] != "broker" {
				t.Errorf("backend_kind filter leaked: got %v", r["backend_kind"])
			}
			if r["id"] == brokerResourceID {
				found = true
			}
		}
		if !found {
			t.Error("freshly created broker resource missing from broker-filtered list")
		}
	})

	// --- 4. FK negative case: bogus broker_provider_id is rejected.
	t.Run("CreateResourceFailsOnUnknownProvider", func(t *testing.T) {
		bad := h.AdminRequest("POST", "/admin/resources", map[string]any{
			"slug":               "broken-fk-resource",
			"uri":                "https://example.test/",
			"backend_kind":       "broker",
			"broker_provider_id": "nonexistent-provider-id",
			"display_name":       "Broken",
			"scopes":             []map[string]any{{"name": "x", "upstream": "x"}},
		})
		defer bad.Body.Close()
		if bad.StatusCode == http.StatusCreated {
			t.Fatalf("create with bogus broker_provider_id should not return 201")
		}
		if bad.StatusCode < 400 || bad.StatusCode >= 500 {
			t.Errorf("expected 4xx, got %d", bad.StatusCode)
		}
	})

	// --- 5. Bad-protocol negative case.
	t.Run("CreateProviderFailsOnBadProtocol", func(t *testing.T) {
		bad := h.AdminRequest("POST", "/admin/broker-providers", map[string]any{
			"slug":         "bad-protocol-provider",
			"display_name": "Bad",
			"protocol":     "smtp",
			"config_data":  map[string]any{},
		})
		defer bad.Body.Close()
		if bad.StatusCode == http.StatusCreated {
			t.Fatalf("create with bogus protocol should not return 201")
		}
	})

	// --- 6. Drive a real exchange so an issuance lands and the
	// audit/forensics surface has rows to read.
	mcpClient := e2e.NewMCPClient(t, h, rs, webAppClientID, "http://localhost:9999/callback")
	tokens := mcpClient.FullFlow(userEmail, userPassword, "tools/echo", true)

	// replace SeedBrokerGrant with the public /connect dance.
	// RunFlowConnect persists a broker_grants row through the same
	// surface an operator using the docs would. Provider slug must
	// match the BrokerProvider created above (github-unified), not the
	// connector's mock-upstream slug ("github").
	h.RunFlowConnect(userEmail, userPassword, "github-unified")

	// replace SeedAgentAttestation with the admin-API
	// equivalent. The Mint resource was created at step 2b; here we
	// drive the per-MCP consent flow to write the consent_grants row
	// for (user, webApp, mcpResource).
	_, _, _ = h.RunFlowC1Consent(
		userEmail, userPassword,
		webAppClientID, "http://localhost:9999/callback",
		mcpResourceSlug,
		[]string{"tools/echo", "repo"},
		[]string{"tools/echo", "repo"},
	)

	// look up the broker_grant id via /admin/users/{id}/grants
	// for later DELETE. Filter by broker_provider_id == bpID to pick
	// out the row that RunFlowConnect just persisted (other test setup
	// does not touch this provider).
	grantID := lookupBrokerGrantID(t, h, userID, bpID)

	// token.TokenTypeAccessToken inlined as its RFC 8693 URN
	// to drop the internal/domain/token import.
	const tokenTypeAccessToken = "urn:ietf:params:oauth:token-type:access_token"

	exch := h.TokenExchangeWithResource(
		mcpServerClientID, mcpSecret,
		tokens.AccessToken, tokenTypeAccessToken,
		"repo",
		"github-unified-repo",
	)
	if exch.AccessToken != "gho_unified_admin" {
		t.Errorf("vended access_token = %q, want gho_unified_admin", exch.AccessToken)
	}

	// --- 7. GET /admin/issuances?user=… returns the row we just minted.
	t.Run("IssuancesAdminListsForwardedToken", func(t *testing.T) {
		ilResp := h.AdminRequest("GET", "/admin/issuances?user="+userID, nil)
		defer ilResp.Body.Close()
		if ilResp.StatusCode != http.StatusOK {
			body, _ := io.ReadAll(ilResp.Body)
			t.Fatalf("list issuances: %d %s", ilResp.StatusCode, body)
		}
		var listResp struct {
			Issuances []map[string]any `json:"issuances"`
			Count     int              `json:"count"`
		}
		if err := json.NewDecoder(ilResp.Body).Decode(&listResp); err != nil {
			t.Fatalf("decode issuances: %v", err)
		}
		if listResp.Count < 1 {
			t.Fatalf("expected at least 1 issuance for user, got %d", listResp.Count)
		}
		var foundBroker bool
		for _, iss := range listResp.Issuances {
			// with the fronting link declared, dispatchFrontedBroker
			// substitutes the source slug ("mcp-0") for the agent's client_id
			// in the issuance row. The pre- assertion
			// expected mcpServerClientID — the agent — but the canonical
			// fronted-dispatch contract logs the gateway identity.
			if iss["client_id"] != "mcp-0" {
				continue
			}
			if iss["backend_kind"] != "broker" {
				continue
			}
			if iss["resource_id"] != brokerResourceID {
				continue
			}
			scopes, _ := iss["scopes"].([]any)
			if len(scopes) != 1 || scopes[0] != "repo" {
				t.Errorf("issuance scopes = %v, want [repo]", scopes)
			}
			foundBroker = true
			break
		}
		if !foundBroker {
			t.Errorf("expected one broker issuance for client=%s resource=%s", mcpServerClientID, brokerResourceID)
		}
	})

	// --- 8. Admin revoke cascades into a consent_required wire error
	// with cause=consent_missing on the next exchange ( wire
	// format for bound-D, no active broker_grants row).
	t.Run("RevokeBrokerGrantBlocksFurtherExchange", func(t *testing.T) {
		delResp := h.AdminRequest("DELETE", "/admin/grants/broker/"+grantID, nil)
		delResp.Body.Close()
		if delResp.StatusCode != http.StatusNoContent {
			t.Fatalf("revoke broker grant: %d", delResp.StatusCode)
		}
		oe := h.TokenExchangeWithResourceExpectError(
			mcpServerClientID, mcpSecret,
			tokens.AccessToken, tokenTypeAccessToken,
			"repo",
			"github-unified-repo",
		)
		if oe.Error != "consent_required" {
			t.Errorf("post-revoke error = %q, want consent_required", oe.Error)
		}
		if oe.Cause != "consent_missing" {
			t.Errorf("post-revoke cause = %q, want consent_missing", oe.Cause)
		}
	})

	// --- 9. Audit-pipeline sample: every  action constant
	// exercised. Audit is sync (verified internal/services/audit.go),
	// so the GET immediately after each mutation finds the row.
	//
	// the audit-action constants are inlined as their
	// wire-format string values (mirroring
	// internal/domain/audit/entity.go) so this file does not need to
	// import internal/domain/audit. expectAtLeastOne therefore takes
	// a string instead of audit.Action.
	t.Run("AuditPipelineRecordsAllNewActions", func(t *testing.T) {
		expectAtLeastOne := func(t *testing.T, action string) {
			t.Helper()
			resp := h.AdminRequest("GET", "/admin/audit?action="+action, nil)
			defer resp.Body.Close()
			if resp.StatusCode != http.StatusOK {
				t.Fatalf("audit list for %q: status %d", action, resp.StatusCode)
			}
			var rows []map[string]any
			if err := json.NewDecoder(resp.Body).Decode(&rows); err != nil {
				t.Fatalf("decode audit list: %v", err)
			}
			if len(rows) == 0 {
				t.Errorf("audit log missing event for action %q (expected ≥1)", action)
			}
		}

		// Already triggered above:
		expectAtLeastOne(t, "resource.created")
		expectAtLeastOne(t, "broker_provider.created")
		expectAtLeastOne(t, "broker_grant.revoked_admin")

		// PATCH the resource to trigger ActionResourcePatched.
		patchResp := h.AdminRequest("PATCH", "/admin/resources/"+brokerResourceID, map[string]any{
			"display_name": "GitHub Repos (renamed)",
		})
		patchResp.Body.Close()
		if patchResp.StatusCode != http.StatusOK {
			t.Fatalf("patch resource: %d", patchResp.StatusCode)
		}
		expectAtLeastOne(t, "resource.patched")

		// PATCH the broker provider to trigger ActionBrokerProviderPatched.
		patchBP := h.AdminRequest("PATCH", "/admin/broker-providers/"+bpID, map[string]any{
			"display_name": "GitHub (unified renamed)",
		})
		patchBP.Body.Close()
		if patchBP.StatusCode != http.StatusOK {
			t.Fatalf("patch broker provider: %d", patchBP.StatusCode)
		}
		expectAtLeastOne(t, "broker_provider.patched")

		// pick an active consent grant to revoke for
		// ActionConsentGrantRevokedAdmin. Multiple are already in place
		// at this point — the FullFlow above wrote one for
		// (user, webApp, rs.ID), and the main-flow RunFlowC1Consent
		// wrote one for (user, webApp, mcpResource.ID). Either works;
		// the original test grabbed `consent_grants[0]` indiscriminately.
		// We filter on revoked_at to skip rows the cascade in the broker-
		// grant revoke step might already have touched (defense in depth
		// — that cascade currently only revokes issuances, not consent
		// grants, but the explicit filter keeps the assertion robust if
		// that contract changes).
		grantsResp := h.AdminRequest("GET", "/admin/users/"+userID+"/grants", nil)
		var grants struct {
			ConsentGrants []map[string]any `json:"consent_grants"`
		}
		if err := json.NewDecoder(grantsResp.Body).Decode(&grants); err != nil {
			t.Fatalf("decode grants: %v", err)
		}
		grantsResp.Body.Close()
		var consentID string
		for _, cg := range grants.ConsentGrants {
			if _, revoked := cg["revoked_at"]; revoked {
				continue
			}
			consentID, _ = cg["id"].(string)
			if consentID != "" {
				break
			}
		}
		if consentID == "" {
			t.Fatalf("expected at least one active consent grant to revoke; got %+v", grants.ConsentGrants)
		}
		revoke := h.AdminRequest("DELETE", "/admin/grants/consent/"+consentID, nil)
		revoke.Body.Close()
		if revoke.StatusCode != http.StatusNoContent {
			t.Fatalf("revoke consent grant: %d", revoke.StatusCode)
		}
		expectAtLeastOne(t, "consent_grant.revoked_admin")

		// Revoke a single issuance for ActionIssuanceRevokedAdmin. The
		// post-revoke list may include rows already revoked by the
		// cascade; pick the first non-revoked one.
		ilResp := h.AdminRequest("GET", "/admin/issuances?user="+userID, nil)
		var issList struct {
			Issuances []map[string]any `json:"issuances"`
		}
		json.NewDecoder(ilResp.Body).Decode(&issList)
		ilResp.Body.Close()
		var issID string
		for _, iss := range issList.Issuances {
			if _, revoked := iss["revoked_at"]; revoked {
				continue
			}
			issID, _ = iss["id"].(string)
			if issID != "" {
				break
			}
		}
		if issID == "" {
			// fallback — re-mint by exchanging once more so
			// the audit step still has a target. Both grants we need
			// were revoked above; reseed via the public surface
			// (RunFlowConnect for the broker_grants row,
			// RunFlowC1Consent for the consent_grants row).
			h.RunFlowConnect(userEmail, userPassword, "github-unified")
			_, _, _ = h.RunFlowC1Consent(
				userEmail, userPassword,
				webAppClientID, "http://localhost:9999/callback",
				mcpResourceSlug,
				[]string{"tools/echo", "repo"},
				[]string{"tools/echo", "repo"},
			)
			h.TokenExchangeWithResource(
				mcpServerClientID, mcpSecret,
				tokens.AccessToken, tokenTypeAccessToken,
				"repo",
				"github-unified-repo",
			)
			ilResp2 := h.AdminRequest("GET", "/admin/issuances?user="+userID, nil)
			json.NewDecoder(ilResp2.Body).Decode(&issList)
			ilResp2.Body.Close()
			for _, iss := range issList.Issuances {
				if _, revoked := iss["revoked_at"]; revoked {
					continue
				}
				issID, _ = iss["id"].(string)
				if issID != "" {
					break
				}
			}
		}
		if issID == "" {
			t.Fatal("no live issuance available to revoke for audit-action exercise")
		}
		revIss := h.AdminRequest("DELETE", "/admin/issuances/"+issID, nil)
		revIss.Body.Close()
		if revIss.StatusCode != http.StatusNoContent {
			t.Fatalf("revoke issuance: %d", revIss.StatusCode)
		}
		expectAtLeastOne(t, "issuance.revoked_admin")

		// ActionResourceDeleted + ActionBrokerProviderDeleted: do these
		// last because the resource has FKs from issuances.
		throwawayBP := h.AdminRequest("POST", "/admin/broker-providers", map[string]any{
			"slug":         "throwaway-provider",
			"display_name": "Throwaway",
			"protocol":     "oauth",
			"config_data":  map[string]any{},
		})
		var tbpBody map[string]any
		json.NewDecoder(throwawayBP.Body).Decode(&tbpBody)
		throwawayBP.Body.Close()
		tbpID, _ := tbpBody["id"].(string)

		throwawayRes := h.AdminRequest("POST", "/admin/resources", map[string]any{
			"slug":         "throwaway-resource",
			"backend_kind": "mint",
			"display_name": "Throwaway Mint",
			"scopes":       []map[string]any{{"name": "tx"}},
		})
		var tresBody map[string]any
		json.NewDecoder(throwawayRes.Body).Decode(&tresBody)
		throwawayRes.Body.Close()
		tresID, _ := tresBody["id"].(string)

		delRes := h.AdminRequest("DELETE", "/admin/resources/"+tresID, nil)
		delRes.Body.Close()
		if delRes.StatusCode != http.StatusNoContent {
			t.Fatalf("delete throwaway resource: %d", delRes.StatusCode)
		}
		delBP := h.AdminRequest("DELETE", "/admin/broker-providers/"+tbpID, nil)
		delBP.Body.Close()
		if delBP.StatusCode != http.StatusNoContent {
			t.Fatalf("delete throwaway broker provider: %d", delBP.StatusCode)
		}
		expectAtLeastOne(t, "resource.deleted")
		expectAtLeastOne(t, "broker_provider.deleted")
	})

	// Defense-in-depth: no consent_grants row should exist for the
	// (webApp, broker_resource_id) tuple — the consent flow keys on
	// the actor MCP resource id, never on a Broker resource id. The
	// check guards against a sibling sub-test (or a future
	// follow-up) accidentally seeding a row at this tuple.
	//
	// read via the /admin/users/{id}/grants endpoint instead
	// of consentGrantStore. We expect ZERO matches — fail loudly if
	// any are found.
	leakResp := h.AdminRequest("GET", "/admin/users/"+userID+"/grants", nil)
	defer leakResp.Body.Close()
	if leakResp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(leakResp.Body)
		t.Fatalf("list user grants for leak check: %d %s", leakResp.StatusCode, body)
	}
	var leakGrants struct {
		ConsentGrants []map[string]any `json:"consent_grants"`
	}
	if err := json.NewDecoder(leakResp.Body).Decode(&leakGrants); err != nil {
		t.Fatalf("decode user grants for leak check: %v", err)
	}
	for _, cg := range leakGrants.ConsentGrants {
		if cg["client_id"] == webAppClientID && cg["resource_id"] == brokerResourceID {
			t.Errorf("unexpected consent_grants row leaked: %+v", cg)
		}
	}
}

// lookupBrokerGrantID fetches /admin/users/{userID}/grants and returns
// the active broker_grants row id whose broker_provider_id matches the
// given UUID. Fails the test if no match is found. Used as the
// public-API replacement for the grantID returned by
// SeedBrokerGrant (which wrote directly to the broker_grant store).
func lookupBrokerGrantID(t *testing.T, h *e2e.TestHarness, userID, providerID string) string {
	t.Helper()
	resp := h.AdminRequest("GET", "/admin/users/"+userID+"/grants", nil)
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		t.Fatalf("list user grants for %s: %d %s", userID, resp.StatusCode, body)
	}
	var grants struct {
		BrokerGrants []map[string]any `json:"broker_grants"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&grants); err != nil {
		t.Fatalf("decode user grants: %v", err)
	}
	for _, bg := range grants.BrokerGrants {
		if bg["broker_provider_id"] != providerID {
			continue
		}
		if _, revoked := bg["revoked_at"]; revoked {
			continue
		}
		id, _ := bg["id"].(string)
		if id != "" {
			return id
		}
	}
	t.Fatalf("no active broker_grants row found for user=%s provider=%s in %+v",
		userID, providerID, grants.BrokerGrants)
	return ""
}
